version: '3.8'

services:
  guestbook:
    build: .
    ports:
      - "8885:5000"
    volumes:
      - guestbook_data:/data
    environment:
      - RESET_PASSWORD=passwort  # ur password here pls

volumes:
  guestbook_data:
